# Generated by Django 3.1.3 on 2020-11-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bg_remove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_img', models.ImageField(upload_to='process/')),
            ],
        ),
        migrations.CreateModel(
            name='Final_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_img', models.ImageField(upload_to='final/')),
            ],
        ),
        migrations.CreateModel(
            name='Og_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='original/')),
            ],
        ),
    ]
