# Generated by Django 3.1.3 on 2020-11-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgSub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='bg/')),
            ],
        ),
    ]
